import type { InArgs } from '@libsql/client';
import { client } from '../config/db.js';

interface AgentTaskSeedRow {
  id: number;
  source: string;
  title: string;
  body: string;
  status: string;
  comment: string | null;
  metadata: string | null;
  pickedUpAt: string | null;
  resolvedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

const AGENT_TASK_SEED: AgentTaskSeedRow[] = [
  {
    id: 1,
    source: 'EMAIL',
    title: 'Show company phone number in the company list view',
    body: 'The phone number is stored but not shown in the company list table. Please add the `phone` column to the company list.',
    status: 'OPEN',
    comment: null,
    metadata: '{"sender":"k.bauer@mueller.de","subject":"Feature request: phone in company list"}',
    pickedUpAt: null,
    resolvedAt: null,
    createdAt: '2026-06-01T09:15:00.000Z',
    updatedAt: '2026-06-01T09:15:00.000Z',
  },
  {
    id: 2,
    source: 'EMAIL',
    title: 'Sort activity list by date descending by default',
    body: 'When I open the activity list for a company, the entries are shown in the order they were created, oldest first. It would make much more sense to show the most recent activities at the top. Please change the default sort order of the activity list to date descending.',
    status: 'OPEN',
    comment: null,
    metadata: '{"sender":"m.hoffmann@fischer.de","subject":"Activity list sort order"}',
    pickedUpAt: null,
    resolvedAt: null,
    createdAt: '2026-06-02T11:30:00.000Z',
    updatedAt: '2026-06-02T11:30:00.000Z',
  },
  {
    id: 3,
    source: 'EMAIL',
    title: 'Make the app look nicer',
    body: 'Hi, the app works but it doesn\'t look great. Can you make it look nicer? Thanks.',
    status: 'OPEN',
    comment: null,
    metadata: '{"sender":"user123@example.com","subject":"UI feedback"}',
    pickedUpAt: null,
    resolvedAt: null,
    createdAt: '2026-06-03T14:00:00.000Z',
    updatedAt: '2026-06-03T14:00:00.000Z',
  },
  {
    id: 4,
    source: 'EMAIL',
    title: 'Fix the broken feature',
    body: 'Something is broken. Please fix it as soon as possible.',
    status: 'OPEN',
    comment: null,
    metadata: '{"sender":"anon@example.com","subject":"Bug report"}',
    pickedUpAt: null,
    resolvedAt: null,
    createdAt: '2026-06-04T08:45:00.000Z',
    updatedAt: '2026-06-04T08:45:00.000Z',
  },
  {
    id: 5,
    source: 'GITHUB_ISSUE',
    title: 'Show total pipeline value on Chancen board',
    body: 'The Chancen list shows individual opportunity values but there is no total anywhere. Please add a summary line or header showing the sum of all `wert` values across all Chancen records, displayed on the Chancen list page header.',
    status: 'OPEN',
    comment: null,
    metadata: '{"issueNumber":42,"labels":["enhancement"]}',
    pickedUpAt: null,
    resolvedAt: null,
    createdAt: '2026-06-04T10:00:00.000Z',
    updatedAt: '2026-06-04T10:00:00.000Z',
  },
  {
    id: 6,
    source: 'GITHUB_ISSUE',
    title: 'Filter persons list by department',
    body: 'The persons list at `/personen` does not support filtering by department (Abteilung). Please add an `abteilungId` query parameter to `GET /api/personen` and wire a department dropdown filter to the frontend persons list page.',
    status: 'OPEN',
    comment: null,
    metadata: '{"issueNumber":57,"labels":["enhancement","backend","frontend"]}',
    pickedUpAt: null,
    resolvedAt: null,
    createdAt: '2026-06-05T09:00:00.000Z',
    updatedAt: '2026-06-05T09:00:00.000Z',
  },
  {
    id: 7,
    source: 'GITHUB_ISSUE',
    title: 'Improve performance',
    body: 'The app feels slow sometimes. Performance should be improved.',
    status: 'OPEN',
    comment: null,
    metadata: '{"issueNumber":63,"labels":["performance"]}',
    pickedUpAt: null,
    resolvedAt: null,
    createdAt: '2026-06-05T13:20:00.000Z',
    updatedAt: '2026-06-05T13:20:00.000Z',
  },
  {
    id: 8,
    source: 'GITHUB_ISSUE',
    title: 'The dashboard is wrong',
    body: 'The dashboard shows wrong data. Please fix it.',
    status: 'OPEN',
    comment: null,
    metadata: '{"issueNumber":71,"labels":["bug"]}',
    pickedUpAt: null,
    resolvedAt: null,
    createdAt: '2026-06-06T07:10:00.000Z',
    updatedAt: '2026-06-06T07:10:00.000Z',
  },
  {
    id: 9,
    source: 'APP_LOG',
    title: 'GET /api/health response missing version field',
    body: 'The health check endpoint GET /api/health returns only { status, timestamp }. Monitoring tooling expects a version field so we can confirm which build is running. The backend package.json already declares "version": "1.0.0". Add a version field to the response object in backend/src/app.ts so the endpoint returns { status, timestamp, version } where version is read from the package.json version string.',
    status: 'OPEN',
    comment: null,
    metadata: '{"level":"WARN","timestamp":"2026-06-07T03:12:44.000Z","requestPath":"/api/health"}',
    pickedUpAt: null,
    resolvedAt: null,
    createdAt: '2026-06-07T03:15:00.000Z',
    updatedAt: '2026-06-07T03:15:00.000Z',
  },
  {
    id: 10,
    source: 'APP_LOG',
    title: 'GET /api/chancen does not support filtering by phase',
    body: 'The GET /api/chancen endpoint accepts sort and pagination but no phase filter query parameter. Every other list endpoint with a categorical field supports filtering (e.g. aktivitaeten by typ). Users need to filter open opportunities. Add an optional phase query parameter (one of NEU, QUALIFIZIERT, ANGEBOT, VERHANDLUNG, GEWONNEN, VERLOREN) to GET /api/chancen in backend/src/routes/chancen.ts and pass it through to chanceService.findAll in backend/src/services/chanceService.ts where a WHERE clause on c.phase should be conditionally appended.',
    status: 'OPEN',
    comment: null,
    metadata: '{"level":"WARN","timestamp":"2026-06-07T08:55:10.000Z","requestPath":"/api/chancen"}',
    pickedUpAt: null,
    resolvedAt: null,
    createdAt: '2026-06-07T09:00:00.000Z',
    updatedAt: '2026-06-07T09:00:00.000Z',
  },
  {
    id: 11,
    source: 'APP_LOG',
    title: 'Intermittent 500 on startup',
    body: 'Sometimes the server returns 500 errors on startup. Happens maybe once a week.',
    status: 'OPEN',
    comment: null,
    metadata: '{"level":"ERROR","timestamp":"2026-06-08T00:00:00.000Z","requestPath":"/"}',
    pickedUpAt: null,
    resolvedAt: null,
    createdAt: '2026-06-08T00:05:00.000Z',
    updatedAt: '2026-06-08T00:05:00.000Z',
  },
  {
    id: 12,
    source: 'APP_LOG',
    title: 'Occasional slow query',
    body: 'Some queries seem slow sometimes. Not sure which ones.',
    status: 'OPEN',
    comment: null,
    metadata: '{"level":"WARN","timestamp":"2026-06-08T12:30:00.000Z","requestPath":"/api"}',
    pickedUpAt: null,
    resolvedAt: null,
    createdAt: '2026-06-08T12:35:00.000Z',
    updatedAt: '2026-06-08T12:35:00.000Z',
  },
  {
    id: 13,
    source: 'ERROR_REPORT',
    title: 'Adresse typ field is stored in DB but never returned by the API',
    body: 'The adresse table has a typ TEXT column (defined in backend/src/config/migrate.ts and in SPECS-database.md) used to classify addresses (e.g. WORK, HOME). However AdresseDTO, AdresseRow, the BASE_QUERY SELECT list, and AdresseCreateSchema in backend/src/services/adresseService.ts and backend/src/utils/validation.ts all omit typ entirely. As a result the field cannot be written on POST/PUT and is never present in GET responses. Add typ to AdresseDTO, AdresseRow, the SELECT in BASE_QUERY, the INSERT and UPDATE statements, and to AdresseCreateSchema as an optional nullable string.',
    status: 'OPEN',
    comment: null,
    metadata: '{"stackTrace":"AdresseDTO missing field: typ\\n    at adresseService.toDTO (backend/src/services/adresseService.ts:41)","environment":"production"}',
    pickedUpAt: null,
    resolvedAt: null,
    createdAt: '2026-06-09T16:00:00.000Z',
    updatedAt: '2026-06-09T16:00:00.000Z',
  },
  {
    id: 14,
    source: 'ERROR_REPORT',
    title: 'GET /api/chancen does not support text search by titel',
    body: 'GET /api/firmen and GET /api/personen both accept a search query parameter that filters by name/firstName/lastName with a LIKE query. GET /api/chancen has no equivalent: chanceService.findAll in backend/src/services/chanceService.ts accepts only pagination and sort, and the route handler in backend/src/routes/chancen.ts never reads a search query param. Users cannot search for a deal by title. Add an optional search query parameter to GET /api/chancen and implement a WHERE LOWER(c.titel) LIKE LOWER(\'%\' || ? || \'%\') clause in chanceService.findAll, following the same pattern already used in firmaService.findAll.',
    status: 'OPEN',
    comment: null,
    metadata: '{"stackTrace":"Feature absent: no search param on GET /api/chancen\\n    at chanceService.findAll (backend/src/services/chanceService.ts:77)","environment":"production"}',
    pickedUpAt: null,
    resolvedAt: null,
    createdAt: '2026-06-10T10:20:00.000Z',
    updatedAt: '2026-06-10T10:20:00.000Z',
  },
  {
    id: 15,
    source: 'ERROR_REPORT',
    title: 'App crashes intermittently on Linux',
    body: 'The app crashes sometimes on Linux servers. We can\'t reproduce it consistently.',
    status: 'OPEN',
    comment: null,
    metadata: '{"stackTrace":"(no stack trace available)","environment":"production"}',
    pickedUpAt: null,
    resolvedAt: null,
    createdAt: '2026-06-11T06:45:00.000Z',
    updatedAt: '2026-06-11T06:45:00.000Z',
  },
  {
    id: 16,
    source: 'ERROR_REPORT',
    title: 'Something fails sometimes on save',
    body: 'Sometimes saving doesn\'t work. Please look into it.',
    status: 'OPEN',
    comment: null,
    metadata: '{"stackTrace":"(no stack trace available)","environment":"unknown"}',
    pickedUpAt: null,
    resolvedAt: null,
    createdAt: '2026-06-12T14:00:00.000Z',
    updatedAt: '2026-06-12T14:00:00.000Z',
  },
  {
    id: 17,
    source: 'EMAIL',
    title: 'Show phone number of contacts in the persons list',
    body: 'The contacts list at /personen shows the email address, company name, and position for each contact, but not the phone number. The `phone` field is stored in the database and returned by the API in the PersonDTO, but the phone column is missing from the persons list table. I have to click into each individual contact just to find their phone number. Please add the `phone` column to the persons list, next to the email column.',
    status: 'OPEN',
    comment: null,
    metadata: '{"sender":"l.zimmermann@bayer-group.de","subject":"Feature request: phone number in contacts list"}',
    pickedUpAt: null,
    resolvedAt: null,
    createdAt: '2026-06-13T08:10:00.000Z',
    updatedAt: '2026-06-13T08:10:00.000Z',
  },
  {
    id: 18,
    source: 'EMAIL',
    title: 'Show website URL in the company list view',
    body: 'The company list at /firmen displays the company name, industry, email address, phone number, and number of contacts. But the website URL is not shown, even though it is stored in the database and returned by the API. I frequently need to check websites for multiple companies and currently have to click into each company detail page. Please add the `website` column to the company list table so it is visible at a glance.',
    status: 'OPEN',
    comment: null,
    metadata: '{"sender":"t.berger@vertrieb-nord.de","subject":"Company list: please show website URL"}',
    pickedUpAt: null,
    resolvedAt: null,
    createdAt: '2026-06-14T09:45:00.000Z',
    updatedAt: '2026-06-14T09:45:00.000Z',
  },
  {
    id: 19,
    source: 'APP_LOG',
    title: 'GET /api/aktivitaeten does not support filtering by firmaId',
    body: 'The GET /api/aktivitaeten endpoint accepts sort and pagination parameters but no firmaId filter. Every other list endpoint with a foreign key link supports filtering by that key (for example, GET /api/personen accepts an abteilungId query parameter). Users need to retrieve all activities for a specific company without loading the full activities list and filtering client-side. Add an optional firmaId query parameter to GET /api/aktivitaeten in backend/src/routes/aktivitaeten.ts and pass it through to aktivitaetService.findAll in backend/src/services/aktivitaetService.ts where a WHERE clause on ak.firmaId should be conditionally appended when firmaId is present.',
    status: 'OPEN',
    comment: null,
    metadata: '{"level":"WARN","timestamp":"2026-06-13T07:22:15.000Z","requestPath":"/api/aktivitaeten"}',
    pickedUpAt: null,
    resolvedAt: null,
    createdAt: '2026-06-13T07:25:00.000Z',
    updatedAt: '2026-06-13T07:25:00.000Z',
  },
  {
    id: 20,
    source: 'APP_LOG',
    title: 'GET /api/aktivitaeten does not support filtering by typ',
    body: 'The GET /api/aktivitaeten endpoint returns all activity records regardless of type. Monitoring and reporting scripts need to filter to a specific activity type to count interactions by channel. The aktivitaet table has a typ column with allowed values ANRUF, EMAIL, MEETING, NOTIZ, AUFGABE. Add an optional typ query parameter to GET /api/aktivitaeten in backend/src/routes/aktivitaeten.ts and pass it through to aktivitaetService.findAll in backend/src/services/aktivitaetService.ts where a WHERE clause on ak.typ should be conditionally appended when the parameter is present and is one of the allowed values.',
    status: 'OPEN',
    comment: null,
    metadata: '{"level":"WARN","timestamp":"2026-06-14T11:05:33.000Z","requestPath":"/api/aktivitaeten"}',
    pickedUpAt: null,
    resolvedAt: null,
    createdAt: '2026-06-14T11:08:00.000Z',
    updatedAt: '2026-06-14T11:08:00.000Z',
  },
];

const INSERT_SQL =
  `INSERT OR IGNORE INTO agent_task (id, source, title, body, status, comment, metadata, pickedUpAt, resolvedAt, createdAt, updatedAt)` +
  ` VALUES (@id, @source, @title, @body, @status, @comment, @metadata, @pickedUpAt, @resolvedAt, @createdAt, @updatedAt)`;

export async function seedAgentTasks(): Promise<void> {
  const stmts = AGENT_TASK_SEED.map((row) => ({
    sql: INSERT_SQL,
    args: row as unknown as InArgs,
  }));

  await client.batch(stmts, 'write');

  console.log(`=== Seeder: agent_task ensured (${AGENT_TASK_SEED.length} rows, INSERT OR IGNORE) ===`);
}
